"""initial_schema

Revision ID: 5b0bf4f18c50
Revises: 
Create Date: 2026-04-12 19:24:35.369774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b0bf4f18c50'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carriers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('mc_number', sa.String(), nullable=False),
    sa.Column('dot_number', sa.String(), nullable=True),
    sa.Column('legal_name', sa.String(), nullable=False),
    sa.Column('dba_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('physical_address', sa.String(), nullable=True),
    sa.Column('is_authorized', sa.Boolean(), nullable=False),
    sa.Column('safety_rating', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('active', 'in_review', 'suspended', 'inactive', name='carrierstatus'), nullable=False),
    sa.Column('source', sa.Enum('fmcsa', 'tms_import', 'manual', name='carriersource'), nullable=False),
    sa.Column('verification_date', sa.DateTime(), nullable=True),
    sa.Column('raw_fmcsa_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mc_number')
    )
    op.create_table('shippers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contact_name', sa.String(), nullable=False),
    sa.Column('contact_email', sa.String(), nullable=False),
    sa.Column('contact_phone', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('loads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('load_id', sa.String(), nullable=False),
    sa.Column('shipper_id', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('origin_lat', sa.Float(), nullable=True),
    sa.Column('origin_lng', sa.Float(), nullable=True),
    sa.Column('destination_lat', sa.Float(), nullable=True),
    sa.Column('destination_lng', sa.Float(), nullable=True),
    sa.Column('pickup_datetime', sa.DateTime(), nullable=False),
    sa.Column('delivery_datetime', sa.DateTime(), nullable=False),
    sa.Column('equipment_type', sa.String(), nullable=False),
    sa.Column('loadboard_rate', sa.Float(), nullable=False),
    sa.Column('max_rate', sa.Float(), nullable=False),
    sa.Column('min_rate', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('commodity_type', sa.String(), nullable=False),
    sa.Column('num_of_pieces', sa.Integer(), nullable=False),
    sa.Column('miles', sa.Float(), nullable=False),
    sa.Column('dimensions', sa.String(), nullable=True),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('available', 'pending', 'covered', 'cancelled', name='loadstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shipper_id'], ['shippers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('load_id')
    )
    op.create_table('quotes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('shipper_id', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('equipment_type', sa.String(), nullable=False),
    sa.Column('market_rate', sa.Float(), nullable=False),
    sa.Column('quoted_rate', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', name='quotestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shipper_id'], ['shippers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calls',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('carrier_id', sa.String(), nullable=True),
    sa.Column('load_id', sa.String(), nullable=True),
    sa.Column('shipper_id', sa.String(), nullable=True),
    sa.Column('mc_number', sa.String(), nullable=False),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='calldirection'), nullable=False),
    sa.Column('call_start', sa.DateTime(), nullable=False),
    sa.Column('call_end', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.Enum('booked', 'rejected', 'no_agreement', 'cancelled', 'carrier_not_authorized', 'no_loads_available', 'transferred', 'in_progress', name='calloutcome'), nullable=False),
    sa.Column('sentiment', sa.Enum('positive', 'neutral', 'negative', name='callsentiment'), nullable=True),
    sa.Column('transcript_summary', sa.Text(), nullable=True),
    sa.Column('transcript_full', sa.JSON(), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('transferred_to_rep', sa.Boolean(), nullable=False),
    sa.Column('happyrobot_call_id', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('use_case', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.ForeignKeyConstraint(['load_id'], ['loads.id'], ),
    sa.ForeignKeyConstraint(['shipper_id'], ['shippers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carrier_load_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('carrier_id', sa.String(), nullable=False),
    sa.Column('load_id', sa.String(), nullable=True),
    sa.Column('origin_region', sa.String(), nullable=False),
    sa.Column('destination_region', sa.String(), nullable=False),
    sa.Column('equipment_type', sa.String(), nullable=False),
    sa.Column('similar_match_count', sa.Integer(), nullable=False),
    sa.Column('last_service_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.ForeignKeyConstraint(['load_id'], ['loads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('negotiations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('call_id', sa.String(), nullable=False),
    sa.Column('load_id', sa.String(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('carrier_offer', sa.Float(), nullable=False),
    sa.Column('carrier_offer_per_mile', sa.Float(), nullable=False),
    sa.Column('system_response', sa.Enum('accept', 'reject', 'counter', name='negotiationresponse'), nullable=False),
    sa.Column('counter_offer', sa.Float(), nullable=True),
    sa.Column('counter_offer_per_mile', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.ForeignKeyConstraint(['load_id'], ['loads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('negotiations')
    op.drop_table('carrier_load_history')
    op.drop_table('calls')
    op.drop_table('quotes')
    op.drop_table('loads')
    op.drop_table('shippers')
    op.drop_table('carriers')
    # ### end Alembic commands ###
