"""add final_price tone is_final to negotiations

Revision ID: 5c3e7a1ff666
Revises: d7f13dc18fae
Create Date: 2026-04-15 00:22:42.645617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c3e7a1ff666'
down_revision: Union[str, Sequence[str], None] = 'd7f13dc18fae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('negotiations', sa.Column('final_price', sa.Float(), nullable=True))
    op.add_column('negotiations', sa.Column('tone', sa.String(), nullable=True))
    op.add_column('negotiations', sa.Column('is_final', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('negotiations', 'is_final')
    op.drop_column('negotiations', 'tone')
    op.drop_column('negotiations', 'final_price')
    # ### end Alembic commands ###
