"""add warning column to negotiations

Revision ID: d7f13dc18fae
Revises: 5b0bf4f18c50
Create Date: 2026-04-14 13:20:13.054721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7f13dc18fae'
down_revision: Union[str, Sequence[str], None] = '5b0bf4f18c50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('negotiations', sa.Column('warning', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('negotiations', 'warning')
    # ### end Alembic commands ###
